export const END_POINTS = {
  LOGIN: '/api/auth/login/',
  REGISTER: '/api/auth/register/',
  FORGOT_PASSWORD: '/api/auth/forgot-password/',
  RESET_PASSWORD: '/api/auth/reset-password/',
  ME: '/api/auth/me/',
  TOKEN_REFRESH: '/api/auth/token/refresh/',
  GOOGLE_AUTH: '/api/auth/google/',
  FACEBOOK_AUTH: '/api/auth/facebook/',
  CHECKIN: '/api/orders/checkin/',
  ORDERS: '/api/orders/',
  ORDER_DETAIL: (orderId: string | number) => `/api/orders/${orderId}/`,
  PUBLIC_EVENTS: '/api/events/public/',
  PUBLIC_EVENTS_UPCOMING: '/api/events/public/upcoming/',
  PUBLIC_EVENT_DETAIL: (eventId: string | number) => `/api/events/public/${eventId}/`,
  STAFF_ASSIGNED_EVENTS: '/api/events/staff-assigned/',
  EVENT_CHECKIN_TICKETS: (eventId: string | number) => `/api/orders/checkin-tickets/${eventId}/`,
  EVENT_CHECKIN_LOGS: (eventId: string | number) => `/api/orders/checkin-logs/${eventId}/`,
  ENQUIRIES: '/api/enquiries/',
}
